# Generated by Django 4.1.4 on 2022-12-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall_main', '0002_shoppingitem_like_shoppingitem_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='like',
            new_name='like_users',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='like_count',
        ),
    ]
