# Generated by Django 4.1.4 on 2022-12-17 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingmall_main', '0004_remove_shoppingitem_like_users_shoppingitem_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='likes',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='like_users',
            field=models.ManyToManyField(related_name='like_shopping', to=settings.AUTH_USER_MODEL),
        ),
    ]
