# Generated by Django 4.1.4 on 2022-12-17 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingmall_main', '0005_remove_shoppingitem_likes_shoppingitem_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_shopping', to=settings.AUTH_USER_MODEL),
        ),
    ]
