# Generated by Django 3.2 on 2022-12-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall_main', '0006_auto_20221219_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
