# Generated by Django 3.2 on 2022-12-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall_main', '0009_auto_20221219_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='subcomment',
            field=models.ManyToManyField(blank=True, to='shoppingmall_main.SubComment'),
        ),
    ]
